In [1]:
from numpy import *


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr5 = np.arange(25).reshape(5, 5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr5[1][2]

7

In [19]:
arr5[arr5 % 2 == 1] = -1
arr5

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1],
       [20, -1, 22, -1, 24]])